### ISSUE TITLE
Error while parsing xcode project for react-native-maps

### ISSUE THREAD

**Issue by nhandyal** [Thinkmill/react-native-schemes-manager#1]
There's an error being raised while fixing [react-native-maps](https://github.com/airbnb/react-native-maps) v0.12.2. I added a little bit of logging to to figure out which file is failing: 
`react-native-maps/ios/Pods/Pods.xcodeproj/project.pbxproj`

The version of Node I'm running is v6.3.0

### Steps to reproduce the behavior

1. create new project 
```
react-native init scheme_manager_test --version react-native@0.38.1
```
2. replace package.json with
```
{
  "name": "scheme_manager_test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "fix-xcode": "react-native-schemes-manager all",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "xcodeSchemes": {
    "Release": [
      "Staging"
    ]
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.38.1",
    "react-native-maps": "0.12.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-native-schemes-manager": "1.0.0-beta.8",
    "react-test-renderer": "15.4.2"
  }
}
```
3. setup project
```
npm install
react-native link
```
4. run fix-xcode
```
npm run fix-xcode
```

### Expected behavior
fix-xcode should run to completion and add a staging configuration to react-native-maps.

### Actual behavior
```
npm run fix-xcode

> scheme_manager_test@0.0.1 fix-xcode /Users/nhandyal/Documents/projects/zest/scheme_manager_test
> react-native-schemes-manager all

Hiding schemes from node_modules xcode projects.
ios/scheme_manager_test.xcodeproj
 ✔ [fix-script]: ios/scheme_manager_test.xcodeproj fixed
 ✔ [fix-libraries]: Release -> Staging created in node_modules/react-native-maps/ios/AirMaps.xcodeproj
 ✔ [fix-libraries]: Release -> Staging created in node_modules/react-native-maps/ios/Pods/GoogleMaps/Example/GoogleMapsDemos.xcodeproj
Failed for filePath:  /Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-maps/ios/Pods/Pods.xcodeproj/project.pbxproj

/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/src/utilities.js:58
				throw e;
				^
SyntaxError: Expected "/*", "//", or "{" but "<" found.
    at peg$buildStructuredError (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/node_modules/xcode/lib/parser/pbxproj.js:412:12)
    at Object.peg$parse [as parse] (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/node_modules/xcode/lib/parser/pbxproj.js:1886:11)
    at pbxProject.parseSync (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/node_modules/xcode/lib/pbxProject.js:46:24)
    at getFilesMatchingGlob.e (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/src/utilities.js:50:13)
    at glob (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/src/utilities.js:40:5)
    at f (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/Users/nhandyal/Documents/projects/zest/scheme_manager_test/node_modules/react-native-schemes-manager/node_modules/glob/glob.js:199:8)
```

**Comment by blargity** [comment]
Thanks @nhandyal for the great reproduction steps. Helped a lot!

I can verify that I'm able to replicate the issue. It's ultimately an upstream issue in node-xcode, so I lodged an issue there: https://github.com/alunny/node-xcode/issues/127

In the meantime though, we don't actually need to manipulate that particular `.xcodeproj` file to achieve what we want to achieve, so I'll exclude it from the script and we should get you back on track until such time as the node-xcode project is able to parse these correctly.

**Comment by blargity** [comment]
I've published `v1.0.0-beta.9` which should resolve this issue. Please let me know if you're still having trouble.

**Comment by corymsmith** [comment]
I'm getting the exact same issue with the project file from `react-native-fbsdk`

**Comment by RobertSheaO** [comment]
@corymsmith and everyone else having this issue. I wrote a Medium article about how to resolve this issue.

https://medium.com/@RobertSheaO/linking-react-native-fbsdk-f043ac133fc0
