### ISSUE TITLE
critical npm install issue

### ISSUE THREAD

**Issue by andpor** [Thinkmill/react-native-schemes-manager#26]
npm install
```

> react-native-schemes-manager@1.0.0 postinstall /Users/xx/node_modules/react-native-schemes-manager
> node index.js verify-config

Options:
  -h, --help  Show help                                                [boolean]

Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/xx/.nvm/versions/node/v4.2.1/bin/node" "/Users/xx/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! react-native-schemes-manager@1.0.0 postinstall: `node index.js verify-config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-schemes-manager@1.0.0 postinstall script 'node index.js verify-config'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-schemes-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js verify-config
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-schemes-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-schemes-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xx/npm-debug.log


---- npm-debug.log

1578 verbose stack Error: react-native-schemes-manager@1.0.1 postinstall: `node index.js verify-config`
1578 verbose stack Exit status 1
1578 verbose stack     at EventEmitter.<anonymous> (/Users/xx/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
1578 verbose stack     at emitTwo (events.js:87:13)
1578 verbose stack     at EventEmitter.emit (events.js:172:7)
1578 verbose stack     at ChildProcess.<anonymous> (/Users/xx/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
1578 verbose stack     at emitTwo (events.js:87:13)
1578 verbose stack     at ChildProcess.emit (events.js:172:7)
1578 verbose stack     at maybeClose (internal/child_process.js:818:16)
1578 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1579 verbose pkgid react-native-schemes-manager@1.0.1
1580 verbose cwd /Users/xx
1581 error Darwin 16.1.0
1582 error argv "/Users/xx/.nvm/versions/node/v4.2.1/bin/node" "/Users/xx/.nvm/versions/node/v4.2.1/bin/npm" "install"
1583 error node v4.2.1
1584 error npm  v3.10.6
1585 error code ELIFECYCLE
1586 error react-native-schemes-manager@1.0.1 postinstall: `node index.js verify-config`
1586 error Exit status 1
1587 error Failed at the react-native-schemes-manager@1.0.1 postinstall script 'node index.js verify-config'.
1587 error Make sure you have the latest version of node.js and npm installed.
1587 error If you do, this is most likely a problem with the react-native-schemes-manager package,
1587 error not with npm itself.
1587 error Tell the author that this fails on your system:
1587 error     node index.js verify-config
1587 error You can get information on how to open an issue for this project with:
1587 error     npm bugs react-native-schemes-manager
1587 error Or if that isn't available, you can get their info via:
1587 error     npm owner ls react-native-schemes-manager
1587 error There is likely additional logging output above.
1588 verbose exit [ 1, true ]


```

**Comment by andpor** [comment]
Could this line with packageJson be causing the issue?

```
module.exports = function verifyConfig () {
	let packageJson = null;
```

**Comment by blargity** [comment]
Howdy,

Looks like you're running on a fairly old version of node which we don't support. Could you try upgrading to a more recent version of node (current version is 8+)?

Here's another issue on another project that should help you do that: https://github.com/JeffreyWay/laravel-mix/issues/264

I'm going to assume that that'll resolve your problem (as it really should) but if you're still having issues after updating please feel free to open another issue.
